### ISSUE TITLE
Confuse of adding different documents to the Docs's dropdowm button 

### ISSUE THREAD

**Issue by Details0824** [ain-soph/trojanzoo_sphinx_theme#14]
I've looked at your documentation demos and it seems that you are adding their links to the dropdowm button in Docs via the unified url naming in GitHub Pages.

https://ain-soph.github.io/trojanzoo_sphinx_theme/
https://ain-soph.github.io/alpsplot/
https://ain-soph.github.io/trojanzoo/

What I'm wondering is whether these documents need to be built separately first into .html files (perhaps done by GitHub Pages).

Because each document has its own conf.py and layout.html. Can I think that they are actually different pages, when clicking on trojanzoo or trojanzoo_sphinx_theme, the pages are built by different conf.py and layout.html etc. Just because it is hosted by GitHub Pages and has a unified url naming format, you can include them on the same page by adjusting github_user and github_repo.

For example, when I use sphinx-autobuild to build Doc A and Doc B on the host loopback address, they are on port 8000 and 8001 of host127.0.0.1. When I include Doc B in the Docs Dropdown of the Doc A page, clicking on Doc B should jump to port 8001.

Since I'm relatively new to network-related processes, my description is confusing. I hope you can reply me whether my understanding is correct, if wrong, what should be the correct principle.

**Comment by ain-soph** [comment]
https://github.com/ain-soph/alpsplot/blob/6bc36a42f39e7a0d2dae08d35136fc39ce5f12c6/docs/source/conf.py#L45-L50

Here's an example. I use relative link because the root `/` is `https://ain-soph.github.io/` for github pages, and `/alpsplot` means `https://ain-soph.github.io/alpsplot`.  
You can also use absolute links. (e.g., `'base': 'https://github.com/ain-soph/base',`)

There is no relationship among links during generation. They don't have to be generated by sphinx or by yourself. It's just a hyperlink jump.

-----------------------------------------------------
It's the same thing for ports. `127.0.0.1:8001` or `localhost:8001` shall work.

----------------------------------------------------
`github_user` and `github_repo` are different things. [`gh_page_url`](https://github.com/ain-soph/alpsplot/blob/6bc36a42f39e7a0d2dae08d35136fc39ce5f12c6/docs/source/conf.py#L31-L34) is only used for setting sphinx property `html_baseurl`.  
Please refer to [sphinx docs](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_baseurl).


[`github_url`](https://github.com/ain-soph/alpsplot/blob/6bc36a42f39e7a0d2dae08d35136fc39ce5f12c6/docs/source/conf.py#L43  ) is used to generate [linkcode](https://github.com/ain-soph/alpsplot/blob/6bc36a42f39e7a0d2dae08d35136fc39ce5f12c6/docs/source/conf.py#L72-L77) and [GitHub button hyperlink](https://github.com/ain-soph/trojanzoo_sphinx_theme/blob/d3a36675c42dc2563f452e8b3d29a04691203a83/trojanzoo_sphinx_theme/layout.html#L124)

**Comment by Details0824** [comment]
Thank you for your detailed answer, I understand.
